[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "https://www.sadewaelektronik.com/*"
  to = "https://sadewaelektronik.com/:splat"
  status = 301
  force = true
